apiVersion: v1
kind: Pod
metadata:
  name: my-mongo-client
  namespace: default
spec:
  containers:
  - name: my-mongo-client
    image: mongo:3.6
    command: ["tail", "-f", "/dev/null"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
