apiVersion: mongodbcommunity.mongodb.com/v1 
kind: MongoDBCommunity 
metadata: 
  name: mongo-replicaset 
  namespace: nirmata
spec: 
  members: 3 
  type: ReplicaSet 
  version: "5.0.15" 
  replicaSetHorizons: 
  - horizon: mongodb-0.mongodb-hs.nirmata.svc.cluster.local:27017 
  - horizon: mongodb-1.mongodb-hs.nirmata.svc.cluster.local:27017 
  - horizon: mongodb-2.mongodb-hs.nirmata.svc.cluster.local:27017 
  security: 
    tls: 
      enabled: true 
      certificateKeySecretRef: 
        name: mongodb-tls 
      caConfigMapRef: 
        name: ca-config-map 

    authentication: 
      modes: ["SCRAM"] 
  users: 
    - name: admin 
      db: admin 
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password 
        name: admin-password 
      roles: 
        - name: clusterAdmin 
          db: admin 
        - name: userAdminAnyDatabase 
          db: admin 
        - name: root 
          db: admin 
      scramCredentialsSecretName: admin-scram 
    - name: dumpUser 
      db: admin 
      passwordSecretRef: # a reference to the secret that will be used to generate the user's password 
        name: dumpuser-password 
      roles: 
        - name: readWriteAnyDatabase 
          db: admin 
      scramCredentialsSecretName: dumpuser-scram 
  additionalMongodConfig: 
    storage.wiredTiger.engineConfig.journalCompressor: zlib 
  statefulSet: 
    spec: 
      #template:
      #  spec:
      #    containers:
      #      - name: "mongodb"
      #        image: ghcr.io/nirmata/mongodb:v2-5.0.15
      volumeClaimTemplates: 
        - metadata: 
            name: data-volume 
          spec: 
            storageClassName: managed-csi
            accessModes: [ "ReadWriteOnce" ] 
            resources: 
              requests: 
                storage: 50Gi 
--- 
apiVersion: v1 
kind: Secret 
metadata: 
  name: admin-password 
  namespace: nirmata 
type: Opaque 
stringData: 
  password: admin-password 
--- 
apiVersion: v1 
kind: Secret 
metadata: 
  name: dumpuser-password 
  namespace: nirmata
type: Opaque 
stringData: 
  password: dumpuser-password 
